version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto8
    build:
      - backend/mvn clean install
    post_build:
      commands:
        - echo Build Completed
artifacts:
  files:
    - backend/target/main-0.0.1-SNAPSHOT.jar
    - backend/scripts/*.sh
    - backend/appspec.yml
  discard-paths: yes
