version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto8
    build:
      - ./mvn clean install
    post_buid:
      commands:
        - echo Build Completed
artifacts:
  files:
    - target/main-0.0.1-SNAPSHOT.jar
    - scripts/*.sh
    - appspec.yml
  discard-paths: yes